(feat) Add leanstorage friendship guide.
leancloud/docs pull request #3748
Opened 2020-11-25 08:30 UTC by nicecui

把之前的「应用内社交」拆分成了「好友关系」和「社交信息流」。

好友关系里面除了原有的关注，还增加了互为好友。

2020-11-25 09:07 UTC, sdjdd commented on views/leanstorage_friendship_guide.md
> +    group: ['idiot'],
别用这个词了吧...

2020-11-25 09:10 UTC, sdjdd commented on views/leanstorage_friendship_guide.md
> +我们允许在 follow 的时候同时传入一个 attribute 列表，用于设置关系的属性，这些属性都将在 `_Follower` 和 `_Followee` 表同时存在：
```suggestion
我们允许在 follow 的时候同时传入一个 attributes 字典，用于设置关系的属性，这些属性都将在 `_Follower` 和 `_Followee` 表同时存在：
```

2020-11-25 09:16 UTC, sdjdd commented on views/leanstorage_friendship_guide.md
> +AV.Friendship.request("tom's objectId")
Tom 在 wiki 文档中有上下文，这里就有点突兀。换成前文用过的 `user_object_id ` 吧。
```suggestion
AV.Friendship.request('user_object_id')
```

2020-11-25 09:31 UTC, sdjdd commented on views/leanstorage_friendship_guide.md
> +  friend: "tom's objectId",
```suggestion
  friend: 'user_object_id',
```

2020-11-25 09:31 UTC, sdjdd commented on views/leanstorage_friendship_guide.md
> +  // requests(AV.Object[]) 是所有申请加 Tom 为好友的请求
```suggestion
query.equalTo('friend', AV.User.current());
// 未处理的申请，其在 _FriendshipRequest 表的 status 的值为 pending
query.equalTo('status', 'pending');
query.find().then((requests) => {
  // requests 是所有申请添加当前用户为好友的请求
```

2020-11-25 09:31 UTC, sdjdd commented on views/leanstorage_friendship_guide.md
> +B 在接受 A 的好友请求时，同样可以添加属性，这些属性会被存储到 `Followee` 表的相应的列中，例如下方的代码会向 B 的数据中的 `group` 列中存入值 `nobody`。
感觉 nobody 这个词也有点... 贬义？（我的锅）

2020-11-25 09:31 UTC, sdjdd commented on views/leanstorage_friendship_guide.md
> +    AV.Friendship.declineRequest(request).then(() => console.log("接受好友请求成功"));
```suggestion
    AV.Friendship.declineRequest(request).then(() => console.log('拒绝好友请求成功'));
```

2020-11-25 09:31 UTC, sdjdd commented on views/leanstorage_friendship_guide.md
> +    AV.Friendship.declineRequest(request).then(() => console.log("接受好友请求成功"));
不确定 API 允不允许这么干，我记得是要把这行数据删掉重新发起请求才行？
```suggestion
    AV.Friendship.acceptRequest(request).then(() => console.log("接受好友请求成功"));
```

2020-11-25 09:45 UTC, weakish requested changes

2020-11-25 09:45 UTC, weakish commented on views/rest_api.md
> +微博有用户互相关注的功能，如果我们用 `_Followee`（用户关注的人） 和 `_Follower`（用户的粉丝） 这两个类来存储用户之间的关注关系{% if node != 'qcloud' %}（我们的 [好友关系开发指南](leanstorage_friendship_guide.html) 已经实现了这样的模型）{% endif %}，我们可以创建一个查询来找到某个用户关注的人发布的
这里可能还是要保留「应用内社交组件」，或者说我们的好友关系功能实现了模型。

2020-11-25 09:45 UTC, weakish commented on views/leanstorage_friendship_guide.md
> +我们使用 `FollowerQuery` 和 `FolloweeQuery` 对关注关系进行查询。`FollowerQuery` 和 `FolloweeQuery` 返回的 `AVQuery` 对象可以象普通的 `AVQuery` 对象那样使用，它们本质上都是查询数据管理平台中的 `_Follower` 和 `_Followee`表，你可以添加 order、skip、limit 以及其他 whe
```suggestion
我们使用 `FollowerQuery` 和 `FolloweeQuery` 对关注关系进行查询。`FollowerQuery` 和 `FolloweeQuery` 返回的 `AVQuery` 对象可以像普通的 `AVQuery` 对象那样使用，它们本质上都是查询数据管理平台中的 `_Follower` 和 `_Followee`表，你可以添加 order、skip、limit 以及其他 where 条件等信息。
```

2020-11-25 09:45 UTC, weakish commented on views/leanstorage_friendship_guide.md
> +好友关系接口向 `_FriendshipRequest` 及 `_Followee` 表存储数据时默认使用 `friendshipACL`，更改其中一个表的 `friendshipACL`，另一张表的 `friendshipACL` 也会随之更改。在应用控制台 -「存储」-「结构化数据」-「_Followee 或 _FriendshipRequest 表」- 「权限」中可以看到默认的 `frie
```suggestion
好友关系接口向 `_FriendshipRequest` 及 `_Followee` 表存储数据时默认使用 `friendshipACL`，更改其中一个表的 `friendshipACL`，另一张表的 `friendshipACL` 也会随之更改。在「应用控制台 > 存储 > 结构化数据 > `_Followee` 或 `_FriendshipRequest` 表 > 权限」中可以看到默认的 `friendshipACL` 设置。其中包含三个选项：
```

2020-11-25 09:45 UTC, weakish commented on views/leanstorage_friendship_guide.md
> +* `_Followee` 表中为用户 B 新增一条好友数据，`user` 值为用户 B，`followee` 值为用户 A，代表着 A 是自己的好友。
上面「B 是自己的好友」，下面「A 是自己的好友」，有点乱。要不然明确写谁是谁的好友，是谁的 `_Followee` 表？

2020-11-25 09:45 UTC, weakish commented on views/leanstorage_friendship_guide.md
> +B 在接受 A 的好友请求时，同样可以添加属性，这些属性会被存储到 `Followee` 表的相应的列中，例如下方的代码会向 B 的数据中的 `group` 列中存入值 `nobody`。
```suggestion
B 在接受 A 的好友请求时，同样可以添加属性，这些属性会被存储到 `_Followee` 表的相应的列中，例如下方的代码会向 B 的数据中的 `group` 列中存入值 `nobody`。
```

2020-11-25 09:45 UTC, weakish commented on views/leanstorage_friendship_guide.md
> +  -H "X-LC-Session: <logged-in-user-sessionToken>" \
之前 REST API 指南中用的是 `<sessionToken>`，下同。

2020-11-25 10:03 UTC, juvenn commented on views/leanstorage_friendship_guide.md
> +  https://{{host}}/1.1/classes/_FriendshipRequest
我这个接口设计的有点丑，想要支持成这样（后面再说吧）：
```suggestion
  https://{{host}}/1.1/users/<user_id>/friendshipRequests
```

2020-11-25 10:03 UTC, juvenn commented on views/leanstorage_friendship_guide.md
> +```
这里还支持 PUT 更新属性。

2020-11-26 02:42 UTC, nicecui commented on views/leanstorage_friendship_guide.md
> +```
噢..这个是直接搬运的老文档，我补充一下。

2020-11-26 02:42 UTC, nicecui commented on views/leanstorage_friendship_guide.md
> +    group: ['idiot'],
好的

2020-11-26 02:43 UTC, nicecui commented on views/leanstorage_friendship_guide.md
> +* 请求中的 User。只有发起请求的用户可以查看或修改自己的数据，其他所有用户均不可对数据进行操作。**注意，write 权限设置为该选项会导致其他人无法接受或拒绝当前用户的好友请求，因为其他用户无法修改当前用户存储到 `_FriendshipRequest` 表的申请数据。**
好

2020-11-26 02:43 UTC, nicecui commented on views/leanstorage_friendship_guide.md
> +* `_Followee` 表中为用户 B 新增一条好友数据，`user` 值为用户 B，`followee` 值为用户 A，代表着 A 是自己的好友。
我想想哈

2020-11-26 02:44 UTC, nicecui commented on views/leanstorage_friendship_guide.md
> +B 在接受 A 的好友请求时，同样可以添加属性，这些属性会被存储到 `Followee` 表的相应的列中，例如下方的代码会向 B 的数据中的 `group` 列中存入值 `nobody`。
当然不是你的锅啦，是我写的

2020-11-26 02:44 UTC, nicecui commented on views/leanstorage_friendship_guide.md
> +    AV.Friendship.declineRequest(request).then(() => console.log("接受好友请求成功"));
API 可以的

2020-11-26 02:47 UTC, nicecui commented on views/rest_api.md
> +微博有用户互相关注的功能，如果我们用 `_Followee`（用户关注的人） 和 `_Follower`（用户的粉丝） 这两个类来存储用户之间的关注关系{% if node != 'qcloud' %}（我们的 [好友关系开发指南](leanstorage_friendship_guide.html) 已经实现了这样的模型）{% endif %}，我们可以创建一个查询来找到某个用户关注的人发布的
这里和信息流没关系，只说的是 Followee  和 Follower 两个表，所以替换成好友关系是可以的。

2020-11-26 03:19 UTC, nicecui commented on views/leanstorage_friendship_guide.md
> +* 请求中的 User。只有发起请求的用户可以查看或修改自己的数据，其他所有用户均不可对数据进行操作。**注意，write 权限设置为该选项会导致其他人无法接受或拒绝当前用户的好友请求，因为其他用户无法修改当前用户存储到 `_FriendshipRequest` 表的申请数据。**
> 「在互为好友的关系中，我们推荐使用 请求中的 user 权限来限制仅当前 user 读写？」

不行，不能推荐这个权限。请看加粗的那一行字，这样会导致好友申请不可用。

2020-11-26 03:36 UTC, juvenn commented on views/leanstorage_friendship_guide.md
> +* 请求中的 User。只有发起请求的用户可以查看或修改自己的数据，其他所有用户均不可对数据进行操作。**注意，write 权限设置为该选项会导致其他人无法接受或拒绝当前用户的好友请求，因为其他用户无法修改当前用户存储到 `_FriendshipRequest` 表的申请数据。**
是这样的，这里的权限是指 Followee 的 ACL ，不是指 _FriendshipRequest 。后者的 ACL 是设置的「共享」，是允许两个人都可以更新和查看的。FriendshipRequest 的 ACL 应该是不可以更改的。

2020-11-26 03:43 UTC, weakish approved these changes

2020-11-26 03:54 UTC, nicecui commented on views/leanstorage_friendship_guide.md
> +* 请求中的 User。只有发起请求的用户可以查看或修改自己的数据，其他所有用户均不可对数据进行操作。**注意，write 权限设置为该选项会导致其他人无法接受或拒绝当前用户的好友请求，因为其他用户无法修改当前用户存储到 `_FriendshipRequest` 表的申请数据。**
试了一下居然可以，那就推荐这么做吧。

2020-11-26 03:56 UTC, juvenn commented on views/leanstorage-faq.md
> +对于 [好友关系](leanstorage_friendship_guide.html)及[社交信息流](status_system.html)，`create` 和 `update` 按照 Status 和 Follower/Followee 的对象数量来计费。
这里总感觉会给用户一种错觉「GET followee 请求不计费」，原意可能只是想表达 Status 仅对 create/update 收费。

2020-11-26 03:56 UTC, juvenn commented on views/rest_api.md
> +微博有用户互相关注的功能，如果我们用 `_Followee`（用户关注的人） 和 `_Follower`（用户的粉丝） 这两个类来存储用户之间的关注关系{% if node != 'qcloud' %}（我们的 [好友关系开发指南](leanstorage_friendship_guide.html) 已经实现了这样的模型）{% endif %}，我们可以创建一个查询来找到某个用户关注的人发布的
```suggestion
微博有用户互相关注的功能，如果我们用 `_Followee`（用户关注的人） 和 `_Follower`（用户的粉丝） 这两个类来存储用户之间的关注关系{% if node != 'qcloud' %}（我们的 [好友关系功能](leanstorage_friendship_guide.html) 已经实现了这样的模型）{% endif %}，我们可以创建一个查询来找到某个用户关注的人发布的微博（`Post` 表中有一个字段 `author` 指向发布者）：
```

2020-11-26 03:56 UTC, juvenn commented on views/leanstorage_friendship_guide.md
> +LeanCloud 将好友关系分为两种。一种是单向关注，例如微博里面被关注者及粉丝，这种方式不需要好友申请，每一个人都可以随时关注另一个人。另一种是互为好友，即双方互相认为对方是自己的朋友后才能成为朋友，在这种方式下 A 需要向 B 申请成为好友，B 同意后双方互为好友。
```suggestion
LeanCloud 将好友关系分为两种。一种是单向关注，例如微博里面被关注者及粉丝，这种方式不需要好友申请，每一个人都可以随时关注另一个人。另一种是互为好友，例如微信好友，需要双方互相认为对方是自己的朋友后才能确立好友关系，在这种方式下 A 需要向 B 申请成为好友，B 同意后双方互为好友。
```

2020-11-26 03:56 UTC, juvenn commented on views/leanstorage_friendship_guide.md
> +修改好友属性和修改普通表的对象相同，详情请参考[更新对象](rest_api.html#更新对象)。
下面 curl 调整后，这句似乎就不使用，可以考虑去掉了。

2020-11-26 04:16 UTC, nicecui commented on views/leanstorage-faq.md
> +对于 [好友关系](leanstorage_friendship_guide.html)及[社交信息流](status_system.html)，`create` 和 `update` 按照 Status 和 Follower/Followee 的对象数量来计费。
不是这样的，意思是说按照「对象数量」来计费，就是说如果 status 目标用户有 1 万人，那么一次发 status 调用就算做 1 万次调用。
查 Followee 和 Follower  表还是一次请求算一次调用，所以我把「好友关系」去掉，只留下「社交信息流」好了

2020-11-26 04:17 UTC, nicecui commented on views/leanstorage_friendship_guide.md
> +  -H "X-LC-Session: <logged-in-user-sessionToken>" \
好的，我改一下

2020-11-26 04:17 UTC, nicecui commented on views/leanstorage_friendship_guide.md
> +修改好友属性和修改普通表的对象相同，详情请参考[更新对象](rest_api.html#更新对象)。
emmm....这样也行

2020-11-26 04:25 UTC, nicecui commented
已经全部改掉啦。

2020-11-26 06:08 UTC, merged