Net standard
leancloud/docs pull request #3777
Opened 2020-12-21 08:55 UTC by onerain88

2020-12-22 03:22 UTC, onerain88 commented
@weakish @nicecui 请帮忙 review 一下，暂时先不 merge

2020-12-22 04:03 UTC, nicecui commented on views/realtime-guide-senior.md
> +    public Task<LCIMSignature> CreateBlacklistSignature(string conversationId, string clientId, IEnumerable<string> memberIds, string action) {
黑名单也需要签名吗？黑名单里的人应该就不能发消息了？

2020-12-22 04:32 UTC, onerain88 commented on views/realtime-guide-beginner.md
> +client.OnMessage = (conv, msg) => {
现在统一成 tom，jerry 和 client 了。

2020-12-22 04:34 UTC, onerain88 commented on views/realtime-guide-senior.md
> +    public Task<LCIMSignature> CreateConversationSignature(string conversationId, string clientId, IEnumerable<string> memberIds, string action) {
CreateStartConversationSignature 是指[创建对话签名](https://leancloud.cn/docs/realtime-guide-senior.html#hash-358945790)
CreateConversationSignature 是指[对话操作签名](https://leancloud.cn/docs/realtime-guide-senior.html#hash883813173)，比如加群，邀请，踢出群

2020-12-22 04:37 UTC, onerain88 commented on views/realtime-guide-senior.md
> +    public Task<LCIMSignature> CreateBlacklistSignature(string conversationId, string clientId, IEnumerable<string> memberIds, string action) {
[黑名单签名](https://leancloud.cn/docs/realtime-guide-senior.html#hash-898490438)

2020-12-22 08:11 UTC, weakish requested changes
:tada:

2020-12-22 08:11 UTC, weakish commented on views/realtime-guide-senior.md
> +LCIMConversationQuery query = new LCIMConversationQuery(tome);
```suggestion
LCIMConversationQuery query = new LCIMConversationQuery(tom);
```

2020-12-22 08:37 UTC, onerain88 commented on views/start.md
> +- [.Net SDK 安装指南](sdk_setup-net-standard.html)
嗯，主要是想保留下之前的文档，看在哪加个指向旧文档的链接

2020-12-22 08:54 UTC, weakish commented on views/start.md
> +- [.Net SDK 安装指南](sdk_setup-net-standard.html)
也行，那旧文档就沿用原来的 URL 不变。可以像 [Java] 一样在 SDK 安装指南上加个说明，指向旧文档，旧文档开头也加上相应说明，指向新文档。

[Java]: https://leancloud.cn/docs/sdk_setup-java.html

2020-12-22 08:55 UTC, weakish approved these changes

2020-12-22 10:09 UTC, nicecui commented on views/realtime-guide-senior.md
> +    public Task<LCIMSignature> CreateConversationSignature(string conversationId, string clientId, IEnumerable<string> memberIds, string action) {
所以能不能改下命名 😂

2020-12-22 10:46 UTC, weakish approved these changes

2020-12-23 06:00 UTC, weakish approved these changes

2020-12-24 03:27 UTC, onerain88 commented on views/realtime-guide-senior.md
> +    public Task<LCIMSignature> CreateConversationSignature(string conversationId, string clientId, IEnumerable<string> memberIds, string action) {
java 也是这个名字，这里只是个「示例」，不是 SDK  API，先保留吧

2020-12-24 03:37 UTC, merged