Add Go Guides
leancloud/docs pull request #3824
Opened 2021-01-26 07:42 UTC by soasurs

- [ ] Object
- [ ] Query
- [ ] File
- [ ] GeoPoint
- [ ] User
- [ ] Hosting
- [ ] Cloud Function
- [ ] Hook

2021-02-28 08:06 UTC, soasurs commented
**查询** 和 **文件** 部分可能需要在后面重构完成之后再次修改。

https://github.com/leancloud/go-sdk/issues/17

https://github.com/leancloud/go-sdk/issues/18

2021-03-01 03:58 UTC, jysperm commented
`templates/include/doc-nav.html` 和 `templates/pages/index.html` 里需要加链接

2021-03-01 04:39 UTC, jysperm reviewed
先大概看了一下云存储部分

2021-03-01 04:39 UTC, jysperm commented on views/leanstorage_guide.tmpl
> +Go SDK 中 `{{ baseObjectName }}` 类型是对于复杂对象的封装，但是由于 Go 的类型系统的特性，开发者不能顺畅的使用 `map[string]interface{}`，还需要进行类型断言，所以我们强烈建议开发者自行定义对象类型，并且将 `{{ baseObjectName }}` 作为元数据嵌入到结构体中，在和 SDK 交互的过程中都使用自行定义的类型，SDK 会尽力
```suggestion
由于 Go 的类型系统的特性，开发者在使用 `map[string]interface{}` 时需要进行类型断言，所以我们强烈建议开发者在与 SDK 交互的过程中使用自行定义的结构体，并且将 `{{ baseObjectName }}` 作为元数据嵌入到结构体中，SDK 会尽可能将对象上的字段绑定到结构体的对应字段上。
```

2021-03-01 04:39 UTC, jysperm commented on views/leanstorage_guide.tmpl
> +在定义自定义类型时，除了要嵌入 `{{ baseObjectName }}` 作为元数据外，还需要对希望使用的 **可导出** 字段加上 **JSON Tag**。
「可导出」具体影响什么，这里需要提一下。

2021-03-01 04:39 UTC, jysperm commented on views/leanstorage_guide.tmpl
> +对于上面 Todo 类型，可以定义新的对象类型:
不如我们把「对象类型」这种表述改成「结构体」？这样会更精确地指代类似其他语言中「类」的这种机制。

2021-03-01 04:39 UTC, jysperm commented on views/leanstorage_guide-go.md
> +{% set baseObjectName = "Object" %}
用 `leancloud.Object`？毕竟在代码里只能这样写的；Python 文档里也是这么写。

2021-03-01 04:39 UTC, jysperm commented on views/leanstorage_guide.tmpl
> +//构建对象
下一段才是构建对象，这段是定义结构体

2021-03-01 04:39 UTC, jysperm commented on views/leanstorage_guide.tmpl
> +leancloud.OpIncrement(1);
```suggestion
leancloud.OpIncrement(1)
```

2021-03-01 04:39 UTC, jysperm commented on views/leanstorage_guide.tmpl
> +在使用 Go SDK 获取已经保存到云端的对象时，我们推荐使用自定义类型对象；如果不想使用自定义类型的对象，也可以直接使用 `{{ baseObjectName }}`。
感觉把两种方式拆分成两个代码库会比较好，分别加以说明这样会比较好。

2021-03-01 04:39 UTC, jysperm commented on views/leanstorage_guide.tmpl
> +如果已经有之前保存的对象，则可以不使用 `Class().ID()` 这样的形式来指定一个对象，使用 `Object()` 来指向一个对象:
感觉下面这段演示太占篇幅了，不如只加一句「如果已经有之前保存的对象，则可以使用 `client.Object(todo).Update` 代替 `client.Class("Todo").ID(id).Update` 来更新对象」。

2021-03-01 04:39 UTC, jysperm commented on views/leanstorage_guide.tmpl
> +    Parent: post,
这行加个注释吧，告诉读者关键在于这一行

2021-03-01 04:39 UTC, jysperm commented on views/leanstorage_guide.tmpl
> +    Parent  Post   `json:"parent"`
这里也加行注释

2021-03-01 04:39 UTC, jysperm commented on views/leanstorage_guide.tmpl
> +if err := client.Class("Student").NewQuery().EqualTo("lastName", "Smith").Find(&results); err != nil {
所以在 EqualTo 里应该用 JSON tag 的字段名？如果是的话这里加一个「注意」提示下读者吧

2021-03-01 04:39 UTC, jysperm commented on views/leanstorage_guide.tmpl
> +// TODO
这里是没写完还是没这个功能

2021-03-01 04:39 UTC, jysperm commented on views/leanstorage_guide.tmpl
>  注意 `{% if platform_name === "Objective-C" %}hasPrefix{% endif %}{% if platform_name === "JavaScript" %}startsWith{% endif %}{% if platform_name === "Python" %}startswith{% endif %}{% if platform_name
这行也需要把 Go 加进入

2021-03-01 04:39 UTC, jysperm commented on views/leanstorage_guide.tmpl
> +// TODO
看起来查询部分好几个地方都没写完

2021-03-01 04:39 UTC, jysperm commented on views/leanstorage_guide.tmpl
> +file, err := c.Files.UploadFromFile("resume.txt")
```suggestion
file, err := client.Files.UploadFromFile("resume.txt")
```

2021-03-01 04:39 UTC, jysperm commented on views/leanstorage_guide.tmpl
> +file, err := c.Files.UploadFromFile("resume.txt")
```suggestion
file, err := client.Files.UploadFromFile("resume.txt")
```

2021-03-01 04:39 UTC, jysperm commented on views/leanstorage_guide.tmpl
> +// TODO
如果没有这个功能的话就写「暂不支持」不要写 TODO

2021-03-01 04:39 UTC, jysperm commented on views/leanstorage_guide.tmpl
> +在使用自定义类型的对象时，只需要填充想要更新的字段即可，其它字段默认会被初始化为零值，在执行更新操作时 SDK 会忽略对象中的零值字段。注意：**如果想要更新某个字段为对应类型的零值，应该将该字段声明为指针类型。**
可以在下面用单独的一小段来解释零值的问题，包括为什么会有这个问题、如何解决，再加一个例子。

2021-03-01 07:24 UTC, soasurs commented on views/leanstorage_guide.tmpl
> +// TODO
`Exist` 应该是 SDK 里还没做。

2021-03-01 07:39 UTC, soasurs commented on views/leanstorage_guide.tmpl
> +在使用 Go SDK 获取已经保存到云端的对象时，我们推荐使用自定义类型对象；如果不想使用自定义类型的对象，也可以直接使用 `{{ baseObjectName }}`。
两个代码库的意思是...？

2021-03-01 08:47 UTC, weakish requested changes

2021-03-01 08:47 UTC, weakish commented on views/leanengine_webhosting_guide.tmpl
> +// 以示例项目使用 echo 作为框架
```suggestion
// 示例项目使用 echo 作为框架
```

2021-03-01 08:47 UTC, weakish commented on views/leanengine_webhosting_guide.tmpl
> +// TODO
```suggestion
// 暂不支持
```

2021-03-01 08:47 UTC, weakish commented on templates/include/doc-nav.html
> +            {% endif %}
```suggestion
```

这些因为没加 Go 代码示例，可以先不列出

2021-03-01 08:47 UTC, weakish commented on views/leanstorage_guide.tmpl
> +
可以加 object、pointer、file、user、geopoint 等的例子

2021-03-01 08:47 UTC, weakish commented on views/leanstorage_guide.tmpl
> +query := client.Class("Account").NewQuery().GreaterThanOrEqualTo("balance", 500)
```suggestion
query := client.Class("Account").NewQuery().GreaterThanOrEqualTo("balance", 100)
```

2021-03-01 08:47 UTC, weakish commented on views/leanstorage_guide.tmpl
> +##### 关于 Go 中的零值
这个层级应该和「有条件更新」同级并移到「有条件更新」前面。

2021-03-01 08:47 UTC, weakish commented on views/leanstorage_guide.tmpl
> +{% if platform_name === "Go" %}
这里漏掉了代码段？

2021-03-01 08:47 UTC, weakish commented on views/leanstorage_guide.tmpl
> +// TODO
暂不支持？

2021-03-01 08:47 UTC, weakish commented on views/leanstorage_guide.tmpl
这里没加 Go 的代码片段？

2021-03-01 08:47 UTC, weakish commented on views/leanstorage_guide.tmpl
下面没加 Go 的代码示例

2021-03-01 08:47 UTC, weakish commented on views/leanstorage_guide.tmpl
> +// TODO
```suggestion
// 暂不支持
```

2021-03-01 08:59 UTC, soasurs commented on views/leanengine_cloudfunction_guide.tmpl
> +if err := leancloud.Run("averageStars", Review{Movie: "夏洛特烦恼"}, &averageStars); err != nil {
手滑写错了，应该是 `leancloud.RPC`。

2021-03-01 09:38 UTC, soasurs commented on views/leanstorage_guide.tmpl
> +
`Object` 不好加，因为 `Object` 的主要作用是获取对象而不是由用户保存数据到 `Object` 上。

`Pointer` 实质上就是 `Object`，用户在嵌入包含 `Object` 的对象到新的类型中的时候，SDK 会自动把对象转成 `Pointer`。

`File` 如果单独写其实不是特比好说明，因为 `File` 还是要和 `Upload` 那一组函数搭配使用的，单独写个 `File` 没什么用处。

`User` 的话，同 `Object`。

其实最根本的原因还是在于 SDK 设计的时候，就没有打算在 `Object` 上持久化存储数据，而是一个远端的 快照。

2021-03-01 10:39 UTC, jysperm commented on views/leanengine_cloudfunction_guide.tmpl
> +`FunctionRequest` 会作为参数传入到云函数中，`FunctionRequest` 上的属性包括：
```suggestion
`leancloud.FunctionRequest` 会作为参数传入到云函数中，`leancloud.FunctionRequest` 上的属性包括：
```

2021-03-01 10:39 UTC, jysperm commented on views/leanengine_cloudfunction_guide.tmpl
>  ### 云函数错误响应码
这个「云函数错误响应码」的段落好像没写

2021-03-01 10:39 UTC, jysperm commented on views/leanengine_cloudfunction_guide.tmpl
> +### `{% if platformName === "Go" %}AfterSave{% endif %}{% if platformName === "Node.js" %}afterUpdate{% endif %}{% if platformName === "Python" %}after_update{% endif %}{% if platformName === "PHP" %
```suggestion
### `{% if platformName === "Go" %}AfterUpdate{% endif %}{% if platformName === "Node.js" %}afterUpdate{% endif %}{% if platformName === "Python" %}after_update{% endif %}{% if platformName === "PHP" %}afterUpdate{% endif %}{% if platformName === "Java" %}afterUpdate{% endif %}{% if platformName === ".NET" %}AfterUpdate{% endif %}`
```

2021-03-01 10:39 UTC, jysperm commented on views/leanengine_cloudfunction_guide.tmpl
> +暂不支持
AfterSave 为啥暂不支持？

2021-03-01 10:39 UTC, jysperm commented on views/leanengine_cloudfunction_guide.tmpl
> +leancloud.OnVerified("sms", func(req *ClassHookRequest) error {
没加代码块（<code>```</code>）

2021-03-01 10:39 UTC, jysperm commented on views/leanengine_webhosting_guide.tmpl
> +云引擎默认提供 Go 1.14.0 的运行环境，如需指定 Go 的版本，请在 `go.mod` 中声明。
还没实现的功能就先不要写了

2021-03-01 10:39 UTC, jysperm commented on views/leanengine_webhosting_guide.tmpl
> +LeanEngine Go 不依赖任何第三方框架，你可以使用你最熟悉的框架进行开发，或者不使用任何框架，但请正确的将 LeanCloud Go SDK 中提供的云引擎相关中间件接入。
```suggestion
你可以使用你最熟悉的框架或不使用任何框架来开发 Go 程序，但需要将 LeanCloud Go SDK 中提供的云引擎中间件正确地接入你的程序中。
```

2021-03-01 10:39 UTC, jysperm commented on views/leanengine_webhosting_guide.tmpl
> +LeanEngine Go 项目必须是 Go Modules 才会正确地被云引擎识别为 Go 项目。
```suggestion
你的 Go 程序需要使用 Go Modules 才能被云引擎识别。
```

2021-03-01 10:39 UTC, jysperm commented on views/leanengine_webhosting_guide.tmpl
> +你的项目需要遵循一定格式才会被云引擎识别并运行。
这句直接删掉就行了

2021-03-03 03:27 UTC, weakish approved these changes

2021-03-04 08:06 UTC, jysperm commented on views/leanstorage_guide.tmpl
> +在使用 Go SDK 获取已经保存到云端的对象时，我们推荐使用自定义类型对象；如果不想使用自定义类型的对象，也可以直接使用 `{{ baseObjectName }}`。
代码块 ...

2021-03-08 05:02 UTC, weakish commented
冲突解决了，先合并了。后续有其他修改可以再提 PR.

2021-03-08 05:02 UTC, merged