新版 C# 云引擎文档
leancloud/docs pull request #3868
Opened 2021-03-19 08:00 UTC by onerain88

2021-03-26 09:18 UTC, weakish requested changes

2021-03-26 09:18 UTC, weakish commented on views/realtime-guide-systemconv.md
> +    Console.WriteLine($"{parameters["peerId"]} online.");
这里其他语言是要往 LeanCache 更新在线状态的，C# 只是打印就和上面的描述不一致了。可以加下和 LeanCache 交互的代码，或者最上面「例如，客户端上线后更新 LeanCache，供查询客户端的实时在线状态」加个 if 分支单独为 C# 写例子描述。

后面下线 hook 同理。

2021-03-29 09:31 UTC, onerain88 commented on views/leanengine_cloudfunction_guide.tmpl
> +    return album;
是这样写的，因为函数定义是
```cs
public static async Task<LCObject> AlbumBeforeDelete(LCObject album)
```
类似于 ts 的
```typescript
async albumBeforeDelete() : Promise<LCObject>
```

2021-03-29 09:34 UTC, onerain88 commented on views/leanengine_webhosting_guide.tmpl
>  ```
在脚手架工程里有[实现](https://github.com/leancloud/dotnet-core-getting-started/blob/3a075ef9b539adf2d7cf40ee99acd418c1245f19/web/Startup.cs#L52)

2021-03-29 09:37 UTC, onerain88 commented on views/leanengine_cloudfunction_guide.tmpl
>  ## 切换云引擎环境
默认行为是指什么呢？

2021-03-29 10:03 UTC, weakish commented on views/leanengine_webhosting_guide.tmpl
>  ```
那可以写下模板项目会默认开启 HTTPS 跳转，如果需要关闭，注释掉某某文件中的某行。

2021-03-29 10:07 UTC, weakish commented on views/leanengine_cloudfunction_guide.tmpl
>  ## 切换云引擎环境
就是在没有特别指定环境（`LCCloud.IsProduction`）、在云引擎以外的环境下调用云函数，C# SDK 发的 `X-LC-Prod` 的默认值是啥。

2021-03-29 10:37 UTC, weakish commented on views/leanengine_cloudfunction_guide.tmpl
>  ## 切换云引擎环境
下面有一句「在 Node.js、PHP、Java 这三个 SDK 下，默认总是调用生产环境的云函数。」，可以在 Java 后面加下「C#」

2021-03-30 02:51 UTC, weakish approved these changes

2021-03-30 02:52 UTC, merged